---
  - name: Retreive swarm master name
    s3:
      profile: default
      bucket: "{{ aws_s3_bucket }}"
      object: "{{ aws_environment }}/{{ aws_instance_prefix }}/Docker/swarm_master"
      dest: /tmp/swarm_master
      mode: get

  - name: Get swarm master name
    shell: cat /tmp/swarm_master
    register: swarm_master

  - name: join workers to swarm
    shell: docker swarm join "{{ swarm_master.stdout }}":2377
    ignore_errors: True
