---
# Download and install EPEL for Centos/RHEL version 7
- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm dest=/tmp/epel.rpm

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel.rpm creates=/etc/yum.repos.d/epel.repo
